version: '2'
services:
    hbinsdatabaseplatform-app:
        image: hbinsdatabaseplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@hbinsdatabaseplatform-oracle:1521:hbinsDatabasePlatform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9701:9701
